Django/shopping2-main/admin/urls.py
from django.urls import path, include
from .views import *

app_name = 'admin'

urlpatterns = [
    path('login/', LoginPage.as_view(), name='login'),
    path('logout/', LogoutPage.as_view(), name='logout'),
    path('', IndexPage.as_view(), name='index'),

    path('order/', OrderPage.as_view(), name='order'),
    path('order/filter/', OrderFilterPage.as_view(), name='orderfilter'),
    path('order/<int:order_id>/', OrderDetailPage.as_view(), name='orderdetail'),
    path('order/submit/<int:order_id>/', OrderDetailSubmitPage.as_view(), name='orderdetailsubmit'),

    path('product/', ProductPage.as_view(), name='product'),
    path('product/search/', ProductSearch.as_view(), name='productsearch'),
    path('product/filter/<str:category_id>/', ProductFilter.as_view(), name='productfilter'),

    path('product/<int:item_id>/', ProductDetailPage.as_view(), name='productdetail'),

    path('product/add/', ProductAddPage.as_view(), name='productadd'),

    path('product/img/update/<int:img_id>/', ProductImgPage.as_view(), name='productimgUpdate'),
    path('product/img/add/', ProductImgAddPage.as_view(), name='productimgAdd'),
    path('product/img/delete/<int:img_id>/', ProductImgDeletePage.as_view(), name='productimgDelete'),

    path('product/attr/update/<int:attr_id>/', ProductAttributePage.as_view(), name='productattributeUpdate'),
    path('product/attr/add/<int:product_id>/', ProductAttributeAddPage.as_view(), name='productattributeAdd'),
    path('product/attr/delete/<int:attr_id>/', ProductAttributeDeletePage.as_view(), name='productattributeDelete'),

    path('product/attrvalue/update/<int:attrval_id>/', ProductAttributeValueUpdatePage.as_view(), name='productattributevalueUpdate'),
    path('product/attrvalue/add/<int:attr_id>/', ProductAttributeValueAddPage.as_view(), name='productattributevalueAdd'),
    path('product/attrvalue/delete/<int:attrval_id>/', ProductAttributeValueDeletePage.as_view(), name='productattributevalueDelete'),

    path('product/variance/add/', ProductVarianceAddPage.as_view(), name='productvarianceAdd'),
    path('product/variance/edit/<int:variance_id>/', ProductVarianceEditPage.as_view(), name='productvarianceEdit'),
    path('product/variance/delete/<int:variance_id>/', ProductVarianceDeletePage.as_view(), name='productvarianceDelete'),

    path('user/', UserPage.as_view(), name='user'),
    path('user/filter/', UserFilterPage.as_view(), name='userfilter'),
    path('user/<int:user_id>/', UserDetailPage.as_view(), name='userdetail'),
    path('user/delete/<int:user_id>/', UserDeletePage.as_view(), name='userdelete'),

    path('myaccount/', MyAccountPage.as_view(), name='myaccount'),
    path('myaccount/editpassword/', MyAccountEditPasswordPage.as_view(), name='myaccounteditpassword'),
    path('myaccount/deactivate/', MyAccountDeactivatePage.as_view(), name='myaccountdeactivate'),

    path('category/', CategoryPage.as_view(), name='category'),
    path('category/<int:category_id>/', CategoryDetailPage.as_view(), name='categorydetail'),
    path('category/add/', CategoryAddPage.as_view(), name='categoryadd'),
    path('category/delete/<int:category_id>/', CategoryDeletePage.as_view(), name='categorydelete'),

    path('statistics/', StatisticsPage.as_view(), name='statistics'),

    path('FAQ/', FAQPage.as_view(), name='FAQ'),
]

Django/shopping2-main/core/urls.py
from django.urls import path, include
from .views import *

app_name = 'shopping'

urlpatterns = [   
    path('', IndexPage.as_view(), name='index'),
    path('login/', LoginPage.as_view(), name='login'),
    path('logout/', LogoutPage.as_view(), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),

    path('catalog/', CatalogPage.as_view(), name='catalog'),
    path('catalog/search/', CatalogSearch.as_view(), name='catalogsearch'),
    # path('catalog/search/All/', views.catalogSearchAll.as_view(), name='catalogsearchall'),
    path('catalog/filter/<str:category_id>/', CatalogFilter.as_view(), name='catalogfilter'),

    path('detail/<int:item_id>/', ItemDetailPage.as_view(), name='itemdetail'),
    path('detail/add/<int:variance_id>/', AddToCart.as_view(), name='addtocart'),
    
    path('cart/', CartPage.as_view(), name='cartpage'),
    path('cart/delete/<str:id>/', CartItemDelete.as_view(), name='cartdeletepage'),
    path('cart/quantityChange/<str:id>/<str:quantity>/', CartItemQuantityChange.as_view(), name='cartquantitypage'),

    path('checkout/',CheckoutPage.as_view(), name='checkout'),
    # path('success/',SuccessPage.as_view(), name='success'),
    
    path('order/', OrderPage.as_view(), name='order'),
    path('order/filter/', OrderFilterPage.as_view(), name='orderfilter'),
    path('order/<int:order_id>/', OrderDetailPage.as_view(), name='orderdetail'),
    path('order/abort/<int:order_id>/', OrderAbortPage.as_view(), name='orderabort'),

    path('review/<int:product_id>/', ReviewPage.as_view(), name='review'),
    path('review/<int:product_id>/', ReviewPage.as_view(), name='review'),

    path('myaccount/', MyAccountPage.as_view(), name='myaccount'),
    path('myaccount/editpassword/', MyAccountEditPasswordPage.as_view(), name='myaccounteditpassword'),
    path('myaccount/deactivate/', MyAccountDeactivatePage.as_view(), name='myaccountdeactivate'),
    
    path('FAQ/', FAQPage.as_view(), name='FAQ'),
]

Django/shopping2-main/draft/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('admin.urls')),
    path('', include('core.urls')),
    path('info/', include('hybrid.urls')),
]

Django/shopping2-main/hybrid/urls.py
from django.urls import path, include
from .views import *

app_name = 'hybrid'

urlpatterns = [
    path('FAQ/', FAQPage.as_view(), name='FAQ'),
    path('termsofservice/', TermsOfServicePage.as_view(), name='termsofservice'),
]

Django/shopping2-main/hybrid/models.py
from django.db import models

# Create your models here.

Django/shopping2-main/hybrid/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.

class FAQPage(View):
    def get(self,request):
        context = {}
        return render(request,'hybrid/FAQpage/FAQ.html', context)

class TermsOfServicePage(View):
    def get(self,request):
        context = {}
        return render(request,'hybrid/termsofservicepage/termsofservice.html', context)

Django/shopping2-main/templates/hybrid/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Shopping</title>

    {%block cssblock%}
    {%endblock%}
</head>
<body>
    {%include 'hybrid/navbar1.html'%}

    {%block content%}
    {%endblock%}

    {%block jsblock%}
    {%endblock%}
    
    {%include 'hybrid/footer.html'%}
</body>
</html>

Django/shopping2-main/templates/hybrid/footer.html
<footer class="page-footer dark">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <h5>Khởi đầu</h5>
                <ul>
                    {%if request.user.id is None%}
                        <li><a href="{%url 'shopping:index'%}">Trang chủ</a></li>
                    {%else%}
                        {%if request.user.is_staff%}
                        <li><a href="{%url 'admin:index'%}">Trang chủ</a></li>
                        {%else%}
                        <li><a href="{%url 'shopping:index'%}">Trang chủ</a></li>
                        {%endif%}
                    {%endif%}
                </ul>
            </div>
            <div class="col-sm-4">
                <h5>Hỗ trợ</h5>
                <ul>
                    <!-- {{request.user}} -->
                    {%if request.user.id is None%}
                        <li><a href="{%url 'hybrid:FAQ'%}">FAQ</a></li>
                    {%else%}
                        {%if request.user.is_staff%}
                        <li><a href="{%url 'admin:FAQ'%}">FAQ</a></li>
                        {%else%}
                        <li><a href="{%url 'shopping:FAQ'%}">FAQ</a></li>
                        {%endif%}
                    {%endif%}
                </ul>
            </div>
            <div class="col-sm-4">
                <h5>Chính sách</h5>
                <ul>
                    <li><a href="{%url 'hybrid:termsofservice'%}">Điều khoản dịch vụ</a></li>
                    <!-- <li><a href="#">Quyền riêng tư</a></li> -->
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <p>© 2022 Copyright Text</p>
    </div>
</footer>

Django/shopping2-main/templates/hybrid/navbar1.html
<nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar">
    <div class="container">
        {%if request.user.is_staff%}
        <a class="navbar-brand logo" href="{%url 'admin:index'%}">Shopping</a>
        {%else%}
        <a class="navbar-brand logo" href="{%url 'shopping:index'%}">Shopping</a>
        {%endif%}
    </div>
</nav>